### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by tzohpilotl** [SashQuasher/1st-Assigment#2]
Man, your page rocks. Really, is very well put together in terms of distribution, color scheme and that hero image at the beggining is awesome. What got me super excited was your `INDEX.htm` file, man, that perfect indentation is neat. There's little to say here but my 2 cents are that you could take your page to the next level by playing more with font weights, faces, and sizes, someone told me that you should use two different fonts at least. Well done, man, keep up the good work!

**Comment by SashQuasher** [comment]
Thanks for the good words. You are right, the text it's kinda lack luster, I will try using a more attractive font.
Thank for the observation.
