### ISSUE TITLE
My personal review

### ISSUE THREAD

**Issue by diegosaul402** [SashQuasher/1st-Assigment#3]
Hi Emmanuel,
I really enjoyed your page, great desing and very fun.
Your page is great, responsive and adapts very well, just a little thing, at short wide window (mobile) your menu items doesn't have background so they hard to read.
![image](https://cloud.githubusercontent.com/assets/14918730/23099347/d195c1a6-f629-11e6-9aad-42f1320c1e55.png)
It is funny beacuse I used the same (I think) template from w3school and works for me, I tested on Opera & Chrome with the same result.
Your code is easy to read but I thing you have a little too much styles hardcoded in your HTML. But I must say: this is a very personal opinion, I am too far to beeing expert on web, so I'm not shure if it's wrong or not.
I noticed you do just 2 commits to your project, I think you must make a commit every time you do a significant change or add nomehing new to your project, git is a really great tool.
Besides this, your page is great I really like what you did. Greetings.

**Comment by SashQuasher** [comment]
Thanks for the review. Wow, I didn't try the design in phone, never minded that,Great observation, thats very important.
Thanks for the review.
