### ISSUE TITLE
Contrast color issues?

### ISSUE THREAD

**Issue by ulisesac4** [SashQuasher/1st-Assigment#4]
Excellent work as always, I love your page and was not expecting nothing less. The real problem that I have is that in your skills section the background color of those bars does not contrast really well with the text within, so I would change for a lighter font color.

A minor thing to note is the H tag use, I may be a little cocky for my part to address this, but I do not really like the use your are using here, H3 tag is not that suitable for a subsection of a page it might be better to use H2 for those purposes, also in your showcase part you are using the same H tag in the subheading place and in each other sub-subsection of that place and it feel a little weird like you are missing a subsection.

Also, it is written "Projects" :)

**Comment by SashQuasher** [comment]
Thanks for the review. I 'm not that good at colors, but I agree with you, I think maybe a gray color will make it work. 

As always all your comments are well received.
